const categoryMapping = {
    "3dprinting": "Services",
    "acaibowls": "Restaurants",
    "accessories": "Services",
    "accountants": "Services",
    "acnetreatment": "Hospitals and Medicine",
    "active": "Active Life",
    "acupuncture": "Hospitals and Medicine",
    "addictionmedicine": "Hospitals and Medicine",
    "adoptionservices": "Services",
    "adult": "Nightlife",
    "adultedu": "Arts and Entertainment",
    "adultentertainment": "Nightlife",
    "advertising": "Services",
    "aerialfitness": "Active Life",
    "aerialtours": "Active Life",
    "aestheticians": "Hospitals and Medicine",
    "afghani": "Restaurants",
    "african": "Restaurants",
    "aircraftdealers": "Services",
    "aircraftrepairs": "Services",
    "airlines": "Public Transportation",
    "airport_shuttles": "Public Transportation",
    "airportlounges": "Public Transportation",
    "airports": "Public Transportation",
    "airportterminals": "Public Transportation",
    "airsoft": "Active Life",
    "alentejo": "Restaurants",
    "algarve": "Restaurants",
    "allergist": "Hospitals and Medicine",
    "amateursportsteams": "Active Life",
    "amusementparks": "Active Life",
    "anesthesiologists": "Hospitals and Medicine",
    "animalassistedtherapy": "Hospitals and Medicine",
    "animalholistic": "Hospitals and Medicine",
    "animalphysicaltherapy": "Hospitals and Medicine",
    "animalshelters": "Services",
    "antiques": "Arts and Entertainment",
    "apartmentagents": "Services",
    "apartments": "Services",
    "appliances": "Services",
    "appraisalservices": "Services",
    "aquariums": "Arts and Entertainment",
    "aquariumservices": "Services",
    "arabian": "Restaurants",
    "arcades": "Arts and Entertainment",
    "archery": "Active Life",
    "architects": "Services",
    "architecturaltours": "Arts and Entertainment",
    "argentine": "Restaurants",
    "artclasses": "Arts and Entertainment",
    "artconsultants": "Arts and Entertainment",
    "artificialturf": "Services",
    "artmuseums": "Arts and Entertainment",
    "artrestoration": "Arts and Entertainment",
    "arts": "Arts and Entertainment",
    "artsandcrafts": "Arts and Entertainment",
    "artschools": "Arts and Entertainment",
    "artsupplies": "Arts and Entertainment",
    "arttours": "Arts and Entertainment",
    "asianfusion": "Restaurants",
    "assistedliving": "Services",
    "astrologers": "Arts and Entertainment",
    "attractionfarms": "Active Life",
    "auctionhouses": "Services",
    "audiologist": "Hospitals and Medicine",
    "australian": "Restaurants",
    "austrian": "Restaurants",
    "auto": "Services",
    "auto_detailing": "Services",
    "autocustomization": "Services",
    "autodamageassessment": "Services",
    "autoelectric": "Services",
    "autoglass": "Services",
    "autoinsurance": "Services",
    "autoloanproviders": "Services",
    "autopartssupplies": "Services",
    "autorepair": "Services",
    "autosecurity": "Services",
    "autoupholstery": "Services",
    "aviationservices": "Services",
    "awnings": "Services",
    "ayurveda": "Hospitals and Medicine",
    "azores": "Restaurants",
    "baby_gear": "Services",
    "badminton": "Active Life",
    "bagels": "Restaurants",
    "baguettes": "Restaurants",
    "bailbondsmen": "Services",
    "bakeries": "Restaurants",
    "bankruptcy": "Services",
    "banks": "Services",
    "barbers": "Services",
    "barreclasses": "Active Life",
    "bars": "Nightlife",
    "bartenders": "Services",
    "bartendingschools": "Services",
    "baseballfields": "Active Life",
    "basketballcourts": "Active Life",
    "bathing_area": "Services",
    "batterystores": "Services",
    "bbq": "Restaurants",
    "beachbars": "Nightlife",
    "beachequipmentrental": "Active Life",
    "beaches": "Active Life",
    "beachvolleyball": "Active Life",
    "beautysvc": "Services",
    "bedbreakfast": "Services",
    "beer_and_wine": "Services",
    "beerbar": "Nightlife",
    "beertours": "Arts and Entertainment",
    "behavioranalysts": "Hospitals and Medicine",
    "beira": "Restaurants",
    "belgian": "Restaurants",
    "bespoke": "Services",
    "bettingcenters": "Nightlife",
    "beverage_stores": "Services",
    "bicyclepaths": "Active Life",
    "bicycles": "Services",
    "bike_repair_maintenance": "Services",
    "bikeassociations": "Active Life",
    "bikeparking": "Services",
    "bikerentals": "Services",
    "bikerepair": "Services",
    "bikes": "Services",
    "bikesharing": "Public Transportation",
    "bikeshop": "Services",
    "biketours": "Active Life",
    "biohazardcleanup": "Services",
    "bistros": "Restaurants",
    "blinds": "Services",
    "blooddonation": "Hospitals and Medicine",
    "blowoutservices": "Services",
    "boatcharters": "Active Life",
    "boatdealers": "Services",
    "boating": "Active Life",
    "boatpartsandsupplies": "Services",
    "boatrepair": "Services",
    "boattours": "Active Life",
    "bobsledding": "Active Life",
    "bocceball": "Active Life",
    "bodycontouring": "Hospitals and Medicine",
    "bodyshops": "Services",
    "bookbinding": "Services",
    "bookstores": "Arts and Entertainment",
    "bootcamps": "Active Life",
    "bowling": "Active Life",
    "boxing": "Active Life",
    "brasseries": "Restaurants",
    "brazilian": "Restaurants",
    "brazilianjiujitsu": "Active Life",
    "breakfast_brunch": "Restaurants",
    "breweries": "Nightlife",
    "brewingsupplies": "Services",
    "brewpubs": "Nightlife",
    "bridal": "Services",
    "british": "Restaurants",
    "bubblesoccer": "Active Life",
    "bubbletea": "Restaurants",
    "buddhist_temples": "Arts and Entertainment",
    "buffets": "Restaurants",
    "buildingsupplies": "Services",
    "bulgarian": "Restaurants",
    "bungeejumping": "Active Life",
    "burgers": "Restaurants",
    "buses": "Public Transportation",
    "businessconsulting": "Services",
    "businessfinancing": "Services",
    "businesslawyers": "Services",
    "busrental": "Public Transportation",
    "busstations": "Public Transportation",
    "bustours": "Arts and Entertainment",
    "butcher": "Services",
    "c_and_mh": "Hospitals and Medicine",
    "cabaret": "Nightlife",
    "cabinetry": "Services",
    "cablecars": "Public Transportation",
    "cafes": "Restaurants",
    "cafeteria": "Restaurants",
    "cakeshop": "Restaurants",
    "campgrounds": "Active Life",
    "candlestores": "Services",
    "candy": "Services",
    "canyoneering": "Active Life",
    "car_dealers": "Services",
    "cardioclasses": "Active Life",
    "cardiology": "Hospitals and Medicine",
    "careercounseling": "Services",
    "carousels": "Arts and Entertainment",
    "carpenters": "Services",
    "carpet_cleaning": "Services",
    "carpeting": "Services",
    "carpetinstallation": "Services",
    "carrental": "Public Transportation",
    "carwash": "Services",
    "casinos": "Nightlife",
    "castles": "Arts and Entertainment",
    "catalan": "Restaurants",
    "catering": "Services",
    "cellphoneaccessories": "Services",
    "ceremonialclothing": "Services",
    "champagne_bars": "Nightlife",
    "cheese": "Services",
    "cheesetastingclasses": "Arts and Entertainment",
    "chickenshop": "Restaurants",
    "childcare": "Services",
    "childcloth": "Services",
    "childproofing": "Services",
    "childrensmuseums": "Arts and Entertainment",
    "chimneysweeps": "Services",
    "chinese": "Restaurants",
    "chinesebazaar": "Arts and Entertainment",
    "chinesemartialarts": "Active Life",
    "chiropractors": "Hospitals and Medicine",
    "chocolate": "Services",
    "choirs": "Arts and Entertainment",
    "christmastrees": "Services",
    "churches": "Arts and Entertainment",
    "churros": "Restaurants",
    "cideries": "Nightlife",
    "circusschools": "Arts and Entertainment",
    "climbing": "Active Life",
    "clockrepair": "Services",
    "clothingrental": "Services",
    "clowns": "Arts and Entertainment",
    "cocktailbars": "Nightlife",
    "coffee": "Restaurants",
    "coffeeroasteries": "Services",
    "coffeeshops": "Restaurants",
    "collegecounseling": "Services",
    "collegeuniv": "Arts and Entertainment",
    "comedyclubs": "Nightlife",
    "comicbooks": "Arts and Entertainment",
    "commercialrealestate": "Services",
    "commissionedartists": "Arts and Entertainment",
    "communitybookbox": "Arts and Entertainment",
    "communitycenters": "Arts and Entertainment",
    "communitygardens": "Active Life",
    "computers": "Services",
    "concept_shops": "Arts and Entertainment",
    "condominiums": "Services",
    "consumerlaw": "Services",
    "contractlaw": "Services",
    "contractors": "Services",
    "convenience": "Services",
    "cookingclasses": "Arts and Entertainment",
    "cookingschools": "Arts and Entertainment",
    "copyshops": "Services",
    "cosmeticdentists": "Hospitals and Medicine",
    "cosmetics": "Services",
    "cosmeticsurgeons": "Hospitals and Medicine",
    "cosmetology_schools": "Arts and Entertainment",
    "costumes": "Arts and Entertainment",
    "countertopinstall": "Services",
    "couriers": "Services",
    "courthouses": "Arts and Entertainment",
    "cprclasses": "Arts and Entertainment",
    "craneservices": "Services",
    "cremationservices": "Services",
    "creperies": "Restaurants",
    "criminaldefense": "Services",
    "cuban": "Restaurants",
    "culturalcenter": "Arts and Entertainment",
    "cupcakes": "Restaurants",
    "currencyexchange": "Services",
    "customcakes": "Services",
    "custommerchandise": "Services",
    "customsbrokers": "Services",
    "czechslovakian": "Restaurants",
    "damagerestoration": "Services",
    "dance_schools": "Arts and Entertainment",
    "danceclubs": "Nightlife",
    "dancestudio": "Arts and Entertainment",
    "dancewear": "Services",
    "datarecovery": "Services",
    "daycamps": "Arts and Entertainment",
    "decksrailing": "Services",
    "delicatessen": "Restaurants",
    "demolitionservices": "Services",
    "dentalhygienists": "Hospitals and Medicine",
    "dentists": "Hospitals and Medicine",
    "departmentsofmotorvehicles": "Public Transportation",
    "deptstores": "Services",
    "dermatology": "Hospitals and Medicine",
    "desserts": "Restaurants",
    "diagnosticimaging": "Hospitals and Medicine",
    "diagnosticservices": "Hospitals and Medicine",
    "dialysisclinics": "Hospitals and Medicine",
    "diamondbuyers": "Services",
    "dietitians": "Hospitals and Medicine",
    "diners": "Restaurants",
    "dinnertheater": "Arts and Entertainment",
    "disabilitylaw": "Services",
    "discgolf": "Active Life",
    "discountstore": "Services",
    "distilleries": "Nightlife",
    "divebars": "Nightlife",
    "diving": "Active Life",
    "divorce": "Services",
    "diyautoshop": "Services",
    "diyfood": "Services",
    "djs": "Arts and Entertainment",
    "dog_parks": "Active Life",
    "dogwalkers": "Services",
    "donuts": "Restaurants",
    "doorsales": "Services",
    "doulas": "Hospitals and Medicine",
    "dramaschools": "Arts and Entertainment",
    "driveintheater": "Arts and Entertainment",
    "driving_schools": "Services",
    "drones": "Arts and Entertainment",
    "drugstores": "Services",
    "dryclean": "Services",
    "drywall": "Services",
    "dutyfreeshops": "Services",
    "earnosethroat": "Hospitals and Medicine",
    "editorialservices": "Services",
    "education": "Arts and Entertainment",
    "educationservices": "Arts and Entertainment",
    "eldercareplanning": "Services",
    "elderlaw": "Services",
    "electricians": "Services",
    "electricitysuppliers": "Services",
    "electronics": "Services",
    "electronicsrepair": "Services",
    "elementaryschools": "Arts and Entertainment",
    "elevatorservices": "Services",
    "embassy": "Arts and Entertainment",
    "embroideryandcrochet": "Arts and Entertainment",
    "emergencymedicine": "Hospitals and Medicine",
    "emergencypethospital": "Hospitals and Medicine",
    "emergencyrooms": "Hospitals and Medicine",
    "employmentagencies": "Services",
    "employmentlawyers": "Services",
    "endocrinologists": "Hospitals and Medicine",
    "endodontists": "Hospitals and Medicine",
    "engraving": "Services",
    "enviroabatement": "Services",
    "eroticmassage": "Services",
    "escapegames": "Arts and Entertainment",
    "estateliquidation": "Services",
    "estatephotography": "Services",
    "estateplanning": "Services",
    "estheticians": "Hospitals and Medicine",
    "ethicgrocery": "Services",
    "ethiopian": "Restaurants",
    "evchargingstations": "Public Transportation",
    "eventphotography": "Services",
    "eventplanning": "Services",
    "eventservices": "Services",
    "excavationservices": "Services",
    "experiences": "Services",
    "eyebrowservices": "Hospitals and Medicine",
    "eyelashservice": "Hospitals and Medicine",
    "fabricstores": "Services",
    "facepainting": "Arts and Entertainment",
    "fado_houses": "Nightlife",
    "familydr": "Hospitals and Medicine",
    "farmequipmentrepair": "Services",
    "farmersmarket": "Services",
    "farmingequipment": "Services",
    "farms": "Active Life",
    "farriers": "Services",
    "fashion": "Services",
    "fencesgates": "Services",
    "fencing": "Active Life",
    "fengshui": "Services",
    "ferries": "Public Transportation",
    "fertility": "Hospitals and Medicine",
    "festivals": "Arts and Entertainment",
    "filipino": "Restaurants",
    "financialadvising": "Services",
    "financialservices": "Services",
    "firedepartments": "Public Services",
    "fireplace": "Services",
    "fireprotection": "Services",
    "firewood": "Services",
    "fireworks": "Arts and Entertainment",
    "firstaidclasses": "Arts and Entertainment",
    "fishing": "Active Life",
    "fishmonger": "Services",
    "fitness": "Active Life",
    "fitnessequipment": "Services",
    "fleamarkets": "Services",
    "flightinstruction": "Services",
    "floatspa": "Hospitals and Medicine",
    "flooring": "Services",
    "floraldesigners": "Services",
    "florists": "Services",
    "flowers": "Services",
    "flyboarding": "Active Life",
    "fondue": "Restaurants",
    "food": "Restaurants",
    "food_court": "Restaurants",
    "foodbanks": "Services",
    "fooddeliveryservices": "Services",
    "foodsafety": "Services",
    "foodstands": "Restaurants",
    "foodtours": "Arts and Entertainment",
    "foodtrucks": "Restaurants",
    "football": "Active Life",
    "formalwear": "Services",
    "foundationrepair": "Services",
    "framing": "Services",
    "freediving": "Active Life",
    "french": "Restaurants",
    "funeralservices": "Services",
    "funfair": "Arts and Entertainment",
    "furclothing": "Services",
    "furniture": "Services",
    "furnitureassembly": "Services",
    "furniturerepair": "Services",
    "galician": "Restaurants",
    "galleries": "Arts and Entertainment",
    "garage_door_services": "Services",
    "gardeners": "Services",
    "gardening": "Services",
    "gardens": "Arts and Entertainment",
    "gastroenterologist": "Hospitals and Medicine",
    "gastropubs": "Nightlife",
    "gaybars": "Nightlife",
    "gelato": "Restaurants",
    "gemstonesandminerals": "Services",
    "general_litigation": "Services",
    "generaldentistry": "Hospitals and Medicine",
    "generalfestivals": "Arts and Entertainment",
    "geneticists": "Hospitals and Medicine",
    "german": "Restaurants",
    "gerontologist": "Hospitals and Medicine",
    "giftshops": "Services",
    "glassandmirrors": "Services",
    "glassblowing": "Arts and Entertainment",
    "gliding": "Active Life",
    "gluten_free": "Restaurants",
    "gokarts": "Active Life",
    "goldbuyers": "Services",
    "golf": "Active Life",
    "golflessons": "Active Life",
    "gourmet": "Services",
    "graphicdesign": "Services",
    "greek": "Restaurants",
    "grillingequipment": "Services",
    "grillservices": "Services",
    "grocery": "Services",
    "groomer": "Services",
    "groutservices": "Services",
    "guamanian": "Restaurants",
    "guesthouses": "Services",
    "guitarstores": "Services",
    "gun_ranges": "Active Life",
    "guns_and_ammo": "Services",
    "gunsmith": "Services",
    "gutterservices": "Services",
    "gymnastics": "Active Life",
    "gyms": "Active Life",
    "habilitativeservices": "Services",
    "hair": "Services",
    "hair_extensions": "Services",
    "hairloss": "Services",
    "hairremoval": "Hospitals and Medicine",
    "hairstylists": "Services",
    "halotherapy": "Hospitals and Medicine",
    "handyman": "Services",
    "hanggliding": "Active Life",
    "hardware": "Services",
    "hats": "Services",
    "hauntedhouses": "Arts and Entertainment",
    "headshops": "Services",
    "health": "Hospitals and Medicine",
    "healthcoach": "Hospitals and Medicine",
    "healthinsurance": "Services",
    "healthmarkets": "Services",
    "healthretreats": "Hospitals and Medicine",
    "healthtrainers": "Hospitals and Medicine",
    "hearing_aids": "Hospitals and Medicine",
    "hearingaidproviders": "Hospitals and Medicine",
    "hepatologists": "Hospitals and Medicine",
    "herbalshops": "Services",
    "herbsandspices": "Services",
    "hifi": "Services",
    "highschools": "Arts and Entertainment",
    "hiking": "Active Life",
    "himalayan": "Restaurants",
    "hindu_temples": "Arts and Entertainment",
    "historicaltours": "Arts and Entertainment",
    "hobbyshops": "Arts and Entertainment",
    "hockeyequipment": "Services",
    "holidaydecorations": "Services",
    "home_inspectors": "Services",
    "homeandgarden": "Services",
    "homeappliancerepair": "Services",
    "homeautomation": "Services",
    "homecleaning": "Services",
    "homedecor": "Services",
    "homedevelopers": "Services",
    "homeenergyauditors": "Services",
    "homehealthcare": "Hospitals and Medicine",
    "homeinsurance": "Services",
    "homenetworkinstall": "Services",
    "homeopathic": "Hospitals and Medicine",
    "homeservices": "Services",
    "hometheatreinstallation": "Services",
    "homewindowtinting": "Services",
    "honduran": "Restaurants",
    "hookah_bars": "Nightlife",
    "horsebackriding": "Active Life",
    "horsequipment": "Services",
    "horseracing": "Arts and Entertainment",
    "hospice": "Hospitals and Medicine",
    "hospitalists": "Hospitals and Medicine",
    "hospitals": "Hospitals and Medicine",
    "hostels": "Services",
    "hot_air_balloons": "Active Life",
    "hotdog": "Restaurants",
    "hotdogs": "Restaurants",
    "hotel_bar": "Nightlife",
    "hotels": "Services",
    "hotelstravel": "Services",
    "hottubandpool": "Services",
    "housingcooperatives": "Services",
    "hungarian": "Restaurants",
    "huntingfishingsupplies": "Services",
    "hvac": "Services",
    "hydroponics": "Services",
    "hydrotherapy": "Hospitals and Medicine",
    "hypnosis": "Hospitals and Medicine",
    "iberian": "Restaurants",
    "icecream": "Restaurants",
    "icedelivery": "Services",
    "immigrationlawyers": "Services",
    "immunodermatologists": "Hospitals and Medicine",
    "importedfood": "Services",
    "indonesian": "Restaurants",
    "indoor_playcenter": "Active Life",
    "indoorlandscaping": "Services",
    "indpak": "Restaurants",
    "infectiousdisease": "Hospitals and Medicine",
    "insulationinstallation": "Services",
    "insurance": "Services",
    "interiordesign": "Services",
    "internalmed": "Hospitals and Medicine",
    "international": "Restaurants",
    "internetcafe": "Services",
    "intlgrocery": "Services",
    "investing": "Services",
    "irish": "Restaurants",
    "irish_pubs": "Nightlife",
    "isps": "Services",
    "italian": "Restaurants",
    "itservices": "Services",
    "jailsandprisons": "Public Services",
    "japanese": "Restaurants",
    "jazzandblues": "Nightlife",
    "jetskis": "Active Life",
    "jewelry": "Services",
    "jewelryrepair": "Services",
    "juicebars": "Restaurants",
    "junkremovalandhauling": "Services",
    "karaoke": "Nightlife",
    "karaokerental": "Arts and Entertainment",
    "karate": "Active Life",
    "kebab": "Restaurants",
    "kickboxing": "Active Life",
    "kids_activities": "Active Life",
    "kidshairsalons": "Services",
    "kiosk": "Services",
    "kitchenandbath": "Services",
    "kitchensupplies": "Services",
    "kiteboarding": "Active Life",
    "knifesharpening": "Services",
    "knittingsupplies": "Services",
    "korean": "Restaurants",
    "laboratorytesting": "Services",
    "lactationservices": "Services",
    "lakes": "Active Life",
    "lancenters": "Services",
    "landmarks": "Arts and Entertainment",
    "landscapearchitects": "Services",
    "landscaping": "Services",
    "landsurveying": "Services",
    "language_schools": "Arts and Entertainment",
    "laotian": "Restaurants",
    "laser_hair_removal": "Hospitals and Medicine",
    "laserlasikeyes": "Hospitals and Medicine",
    "lasertag": "Arts and Entertainment",
    "latin": "Restaurants",
    "laundromat": "Services",
    "laundryservices": "Services",
    "lawn_bowling": "Active Life",
    "lawyers": "Services",
    "leather": "Services",
    "lebanese": "Restaurants",
    "legalservices": "Services",
    "libraries": "Arts and Entertainment",
    "liceservices": "Services",
    "lifecoach": "Hospitals and Medicine",
    "lighting": "Services",
    "lightingstores": "Services",
    "limos": "Services",
    "linens": "Services",
    "lingerie": "Services",
    "livestocksupply": "Services",
    "localflavor": "Arts and Entertainment",
    "localservices": "Services",
    "locksmiths": "Services",
    "lounges": "Nightlife",
    "luggage": "Services",
    "luggagestorage": "Services",
    "macarons": "Restaurants",
    "machinerental": "Services",
    "madeira": "Restaurants",
    "magicians": "Arts and Entertainment",
    "mags": "Services",
    "makerspaces": "Arts and Entertainment",
    "makeupartists": "Services",
    "marchingbands": "Arts and Entertainment",
    "marketing": "Services",
    "markets": "Services",
    "marketstalls": "Services",
    "martialarts": "Active Life",
    "masonry_concrete": "Services",
    "massage": "Hospitals and Medicine",
    "massage_schools": "Arts and Entertainment",
    "massage_therapy": "Hospitals and Medicine",
    "massmedia": "Services",
    "matchmakers": "Services",
    "maternity": "Hospitals and Medicine",
    "mattresses": "Services",
    "mauritius": "Restaurants",
    "meats": "Services",
    "medcenters": "Hospitals and Medicine",
    "media": "Services",
    "medicallaw": "Services",
    "medicalspa": "Hospitals and Medicine",
    "medicalsupplies": "Services",
    "medicaltransportation": "Services",
    "meditationcenters": "Hospitals and Medicine",
    "mediterranean": "Restaurants",
    "memorycare": "Services",
    "menscloth": "Services",
    "menshair": "Services",
    "metaldetectorservices": "Services",
    "metalfabricators": "Services",
    "metrostations": "Public Transportation",
    "mexican": "Restaurants",
    "mideastern": "Restaurants",
    "midwives": "Hospitals and Medicine",
    "militarysurplus": "Services",
    "minho": "Restaurants",
    "mini_golf": "Active Life",
    "mobilehomes": "Services",
    "mobilephonerepair": "Services",
    "mobilephones": "Services",
    "modern_european": "Restaurants",
    "montessori": "Arts and Entertainment",
    "moroccan": "Restaurants",
    "mortgagebrokers": "Services",
    "mortgagelenders": "Services",
    "mortuaryservices": "Services",
    "mosques": "Arts and Entertainment",
    "motorcycle_rental": "Public Transportation",
    "motorcycledealers": "Services",
    "motorcyclepartsandsupplies": "Services",
    "motorcyclerepair": "Services",
    "motorcyclinggear": "Services",
    "mountainbiking": "Active Life",
    "movers": "Services",
    "movietheaters": "Arts and Entertainment",
    "muaythai": "Active Life",
    "museums": "Arts and Entertainment",
    "musicalinstrumentsandteachers": "Arts and Entertainment",
    "musicians": "Arts and Entertainment",
    "musicinstrumentservices": "Arts and Entertainment",
    "musicproduction": "Arts and Entertainment",
    "musicvenues": "Arts and Entertainment",
    "musicvideo": "Arts and Entertainment",
    "mystics": "Arts and Entertainment",
    "nailtechnicians": "Hospitals and Medicine",
    "nannys": "Services",
    "naturalgassuppliers": "Services",
    "naturopathic": "Hospitals and Medicine",
    "nephrologists": "Hospitals and Medicine",
    "neurologist": "Hospitals and Medicine",
    "neuropathologists": "Hospitals and Medicine",
    "neurotologists": "Hospitals and Medicine",
    "nicaraguan": "Restaurants",
    "nightlife": "Nightlife",
    "nonprofit": "Services",
    "noodles": "Restaurants",
    "notaries": "Services",
    "nudist": "Arts and Entertainment",
    "nursepractitioner": "Hospitals and Medicine",
    "nursingschools": "Hospitals and Medicine",
    "nutritionists": "Hospitals and Medicine",
    "obgyn": "Hospitals and Medicine",
    "observatories": "Arts and Entertainment",
    "occupationaltherapy": "Hospitals and Medicine",
    "officecleaning": "Services",
    "officeequipment": "Services",
    "officiants": "Services",
    "oilchange": "Services",
    "oncologist": "Hospitals and Medicine",
    "opera": "Arts and Entertainment",
    "opthamalogists": "Hospitals and Medicine",
    "opticians": "Services",
    "optometrists": "Hospitals and Medicine",
    "oralsurgeons": "Hospitals and Medicine",
    "organic_stores": "Services",
    "oriental": "Restaurants",
    "orthodontists": "Hospitals and Medicine",
    "orthopedists": "Hospitals and Medicine",
    "osteopathicphysicians": "Hospitals and Medicine",
    "othersalons": "Services",
    "otologists": "Hospitals and Medicine",
    "outdoorfurniture": "Services",
    "outdoorgear": "Services",
    "outdoormovies": "Arts and Entertainment",
    "outdoorpowerequipmentservices": "Services",
    "outlet_stores": "Services",
    "packingsupplies": "Services",
    "paddleboarding": "Active Life",
    "painmanagement": "Hospitals and Medicine",
    "paintball": "Active Life",
    "painters": "Services",
    "pakistani": "Restaurants",
    "panasian": "Restaurants",
    "pancakes": "Restaurants",
    "paragliding": "Active Life",
    "parasailing": "Active Life",
    "parentingclasses": "Arts and Entertainment",
    "parking": "Public Transportation",
    "parks": "Active Life",
    "partycharacters": "Arts and Entertainment",
    "partyequipmentrentals": "Services",
    "partysupplies": "Services",
    "passportvisaservices": "Services",
    "patentlaw": "Services",
    "pathologists": "Hospitals and Medicine",
    "patiocoverings": "Services",
    "pawn": "Services",
    "paydayloans": "Services",
    "pediatric_dentists": "Hospitals and Medicine",
    "pediatricians": "Hospitals and Medicine",
    "perfume": "Services",
    "periodontists": "Hospitals and Medicine",
    "permanentmakeup": "Hospitals and Medicine",
    "persian": "Restaurants",
    "personal_injury": "Services",
    "personal_shopping": "Services",
    "personalassistants": "Services",
    "personalchefs": "Services",
    "pest_control": "Services",
    "pet_sitting": "Services",
    "pet_training": "Services",
    "petadoption": "Services",
    "petboarding": "Services",
    "petcremation": "Services",
    "pethospice": "Services",
    "petinsurance": "Services",
    "petphotography": "Services",
    "pets": "Services",
    "petservices": "Services",
    "petstore": "Services",
    "petwasteremoval": "Services",
    "pharmacy": "Hospitals and Medicine",
    "phlebologists": "Hospitals and Medicine",
    "photoboothrentals": "Services",
    "photoclasses": "Arts and Entertainment",
    "photographers": "Services",
    "photographystores": "Services",
    "physicaltherapy": "Hospitals and Medicine",
    "physicians": "Hospitals and Medicine",
    "pianobars": "Nightlife",
    "pianoservices": "Services",
    "pianostores": "Services",
    "piercing": "Hospitals and Medicine",
    "pilates": "Active Life",
    "pizza": "Restaurants",
    "placentaencapsulation": "Hospitals and Medicine",
    "planetarium": "Arts and Entertainment",
    "plasticsurgeons": "Hospitals and Medicine",
    "playgrounds": "Active Life",
    "playsets": "Services",
    "plumbing": "Services",
    "plus_size_fashion": "Services",
    "podiatrists": "Hospitals and Medicine",
    "poke": "Restaurants",
    "policedepartments": "Public Services",
    "polish": "Restaurants",
    "poolbilliards": "Active Life",
    "poolcleaners": "Services",
    "poolhalls": "Active Life",
    "poolservice": "Services",
    "portabletoiletservices": "Services",
    "portuguese": "Restaurants",
    "postoffices": "Public Services",
    "prenatal": "Hospitals and Medicine",
    "preschools": "Arts and Entertainment",
    "pressurewashers": "Services",
    "pretzels": "Restaurants",
    "preventivemedicine": "Hospitals and Medicine",
    "printmedia": "Services",
    "privateinvestigation": "Services",
    "privatejetcharter": "Public Transportation",
    "privateschools": "Arts and Entertainment",
    "privatetutors": "Arts and Entertainment",
    "proctologist": "Hospitals and Medicine",
    "professional": "Services",
    "propane": "Services",
    "propertymgmt": "Services",
    "psychiatrists": "Hospitals and Medicine",
    "psychic_astrology": "Arts and Entertainment",
    "psychicmediums": "Arts and Entertainment",
    "psychics": "Arts and Entertainment",
    "psychoanalysts": "Hospitals and Medicine",
    "psychologists": "Hospitals and Medicine",
    "publicart": "Arts and Entertainment",
    "publicmarkets": "Services",
    "publicplazas": "Arts and Entertainment",
    "publicrelations": "Services",
    "publicservicesgovt": "Public Services",
    "publictransport": "Public Transportation",
    "pubs": "Nightlife",
    "pulmonologist": "Hospitals and Medicine",
    "qigong": "Active Life",
    "racetracks": "Active Life",
    "radiologists": "Hospitals and Medicine",
    "radiostations": "Services",
    "rafting": "Active Life",
    "ramen": "Restaurants",
    "raw_food": "Restaurants",
    "realestate": "Services",
    "realestateagents": "Services",
    "realestatelawyers": "Services",
    "realestatesvcs": "Services",
    "record_labels": "Arts and Entertainment",
    "recording_studios": "Arts and Entertainment",
    "recreation": "Active Life",
    "recyclingcenter": "Services",
    "refinishing": "Services",
    "reflexology": "Hospitals and Medicine",
    "registrationservices": "Services",
    "registry_office": "Public Services",
    "rehabilitation_center": "Hospitals and Medicine",
    "reiki": "Hospitals and Medicine",
    "religiousitems": "Services",
    "religiousorgs": "Arts and Entertainment",
    "religiousschools": "Arts and Entertainment",
    "rentfurniture": "Services",
    "reproductivehealthservices": "Hospitals and Medicine",
    "resorts": "Services",
    "restaurants": "Restaurants",
    "reststops": "Public Transportation",
    "retinaspecialists": "Hospitals and Medicine",
    "retirement_homes": "Services",
    "reunion": "Arts and Entertainment",
    "reupholstery": "Services",
    "rhematologists": "Hospitals and Medicine",
    "ribatejo": "Restaurants",
    "rock_climbing": "Active Life",
    "rodizios": "Restaurants",
    "roofing": "Services",
    "rotisserie_chicken": "Restaurants",
    "rugs": "Services",
    "russian": "Restaurants",
    "rvrental": "Public Transportation",
    "rvrepair": "Services",
    "safestores": "Services",
    "safetyequipment": "Services",
    "sailing": "Active Life",
    "salad": "Restaurants",
    "salumerie": "Services",
    "sandwiches": "Restaurants",
    "saunas": "Services",
    "scooterrentals": "Public Transportation",
    "scootertours": "Arts and Entertainment",
    "screen_printing_tshirt_printing": "Services",
    "screenprinting": "Services",
    "scuba": "Active Life",
    "seafood": "Restaurants",
    "seafoodmarkets": "Services",
    "seasonaldecorservices": "Services",
    "security": "Services",
    "securitysystems": "Services",
    "selfdefenseclasses": "Active Life",
    "selfstorage": "Services",
    "seniorcenters": "Services",
    "septicservices": "Services",
    "servicestations": "Public Transportation",
    "sessionphotography": "Services",
    "sewingalterations": "Services",
    "sextherapists": "Hospitals and Medicine",
    "sharedofficespaces": "Services",
    "shedsandoutdoorstorage": "Services",
    "shipping_centers": "Services",
    "shoerepair": "Services",
    "shoes": "Services",
    "shoeshine": "Services",
    "shopping": "Services",
    "shoppingcenters": "Services",
    "shoppingpassages": "Services",
    "shutters": "Services",
    "signature_cuisine": "Restaurants",
    "signmaking": "Services",
    "sikhtemples": "Arts and Entertainment",
    "silentdisco": "Arts and Entertainment",
    "skate_parks": "Active Life",
    "skateshops": "Services",
    "skatingrinks": "Active Life",
    "skiing": "Active Life",
    "skincare": "Hospitals and Medicine",
    "skiresorts": "Active Life",
    "skischools": "Active Life",
    "skydiving": "Active Life",
    "sledding": "Active Life",
    "sleepspecialists": "Hospitals and Medicine",
    "sleepwear": "Services",
    "smog_check_stations": "Services",
    "smokehouse": "Restaurants",
    "snorkeling": "Active Life",
    "snowremoval": "Services",
    "social_clubs": "Arts and Entertainment",
    "socialsecuritylaw": "Services",
    "softwaredevelopment": "Services",
    "solarinstallation": "Services",
    "sommelierservices": "Services",
    "soup": "Restaurants",
    "souvenirs": "Services",
    "spanish": "Restaurants",
    "spas": "Hospitals and Medicine",
    "speakeasies": "Nightlife",
    "specialbikes": "Services",
    "specialed": "Arts and Entertainment",
    "specialtyschools": "Arts and Entertainment",
    "speech_therapists": "Hospitals and Medicine",
    "speechtraining": "Arts and Entertainment",
    "spiritual_shop": "Arts and Entertainment",
    "sport_equipment_hire": "Active Life",
    "sportgoods": "Active Life",
    "sports_clubs": "Active Life",
    "sportsbars": "Nightlife",
    "sportsmed": "Hospitals and Medicine",
    "sportsteams": "Active Life",
    "sportswear": "Active Life",
    "spraytanning": "Hospitals and Medicine",
    "srilankan": "Restaurants",
    "stadiumsarenas": "Active Life",
    "stationery": "Services",
    "steak": "Restaurants",
    "stereo_installation": "Services",
    "stockings": "Services",
    "stonemasons": "Services",
    "streetart": "Arts and Entertainment",
    "streetvendors": "Services",
    "stripclubs": "Nightlife",
    "stripteasedancers": "Nightlife",
    "structuralengineers": "Services",
    "stucco": "Services",
    "summer_camps": "Active Life",
    "sunglasses": "Services",
    "surfing": "Active Life",
    "surflifesaving": "Active Life",
    "surfschools": "Active Life",
    "surfshop": "Services",
    "surgeons": "Hospitals and Medicine",
    "sushi": "Restaurants",
    "swimminglessons": "Active Life",
    "swimmingpools": "Active Life",
    "swimwear": "Services",
    "synagogues": "Arts and Entertainment",
    "syrian": "Restaurants",
    "tabernas": "Restaurants",
    "tablaoflamenco": "Arts and Entertainment",
    "tabletopgames": "Arts and Entertainment",
    "tableware": "Services",
    "taekwondo": "Active Life",
    "taichi": "Active Life",
    "talentagencies": "Services",
    "tanning": "Hospitals and Medicine",
    "tanningbeds": "Hospitals and Medicine",
    "tapas": "Restaurants",
    "tapasmallplates": "Restaurants",
    "tastingclasses": "Arts and Entertainment",
    "tattoo": "Services",
    "tattooremoval": "Hospitals and Medicine",
    "taxidermy": "Services",
    "taxis": "Public Transportation",
    "taxoffice": "Public Services",
    "taxservices": "Services",
    "tcm": "Hospitals and Medicine",
    "tea": "Restaurants",
    "teachersupplies": "Services",
    "teambuilding": "Services",
    "teethwhitening": "Hospitals and Medicine",
    "telecommunications": "Services",
    "televisionserviceproviders": "Services",
    "televisionstations": "Services",
    "tenantlaw": "Services",
    "tennis": "Active Life",
    "testprep": "Services",
    "thai": "Restaurants",
    "theater": "Arts and Entertainment",
    "threadingservices": "Hospitals and Medicine",
    "thrift_stores": "Services",
    "tickets": "Services",
    "ticketsales": "Services",
    "tikibars": "Nightlife",
    "tires": "Services",
    "tobaccoshops": "Services",
    "tours": "Arts and Entertainment",
    "towing": "Services",
    "townhall": "Public Services",
    "toxicologists": "Hospitals and Medicine",
    "toys": "Services",
    "tradamerican": "Restaurants",
    "tradclothing": "Services",
    "tradefairs": "Arts and Entertainment",
    "trailerrental": "Services",
    "trailerrepair": "Services",
    "trains": "Public Transportation",
    "trainstations": "Public Transportation",
    "trampoline": "Active Life",
    "translationservices": "Services",
    "transmissionrepair": "Services",
    "transport": "Public Transportation",
    "tras_os_montes": "Restaurants",
    "travelagents": "Services",
    "travelservices": "Services",
    "treeservices": "Services",
    "trophyshops": "Services",
    "truck_rental": "Services",
    "truckdealers": "Services",
    "tuina": "Hospitals and Medicine",
    "turkish": "Restaurants",
    "tutoring": "Arts and Entertainment",
    "tvmounting": "Services",
    "ukrainian": "Restaurants",
    "ultrasoundimagingcenters": "Hospitals and Medicine",
    "underseamedicine": "Hospitals and Medicine",
    "uniforms": "Services",
    "university_housing": "Public Services",
    "unofficialyelpevents": "Arts and Entertainment",
    "urgent_care": "Hospitals and Medicine",
    "urologists": "Hospitals and Medicine",
    "usedbooks": "Services",
    "usedcardealers": "Services",
    "utilities": "Services",
    "vacation_rentals": "Services",
    "vacationrentalagents": "Services",
    "vapeshops": "Services",
    "vascularmedicine": "Hospitals and Medicine",
    "vegan": "Restaurants",
    "vegetarian": "Restaurants",
    "vehicleshipping": "Services",
    "vehiclewraps": "Services",
    "venezuelan": "Restaurants",
    "venues": "Arts and Entertainment",
    "vermouthbars": "Nightlife",
    "vet": "Hospitals and Medicine",
    "videoandgames": "Arts and Entertainment",
    "videofilmproductions": "Arts and Entertainment",
    "videogamestores": "Arts and Entertainment",
    "videographers": "Arts and Entertainment",
    "vietnamese": "Restaurants",
    "vintage": "Services",
    "vinyl_records": "Services",
    "virtualrealitycenters": "Arts and Entertainment",
    "visitorcenters": "Services",
    "vitaminssupplements": "Services",
    "vocalcoach": "Arts and Entertainment",
    "vocation": "Arts and Entertainment",
    "waffles": "Restaurants",
    "waldorfschools": "Arts and Entertainment",
    "walkinclinics": "Hospitals and Medicine",
    "walkingtours": "Arts and Entertainment",
    "wallpapering": "Services",
    "watch_repair": "Services",
    "watches": "Services",
    "waterheaterinstallrepair": "Services",
    "waterparks": "Arts and Entertainment",
    "waterproofing": "Services",
    "waterpurification": "Services",
    "watersuppliers": "Services",
    "waxing": "Hospitals and Medicine",
    "web_design": "Services",
    "wedding_planning": "Services",
    "weightlosscenters": "Hospitals and Medicine",
    "whalewatchingtours": "Arts and Entertainment",
    "wheelrimrepair": "Services",
    "whiskeybars": "Nightlife",
    "wholesale_stores": "Services",
    "wigs": "Services",
    "wildlifecontrol": "Services",
    "windowsinstallation": "Services",
    "windowwashing": "Services",
    "windshieldinstallrepair": "Services",
    "wine_bars": "Nightlife",
    "wineries": "Nightlife",
    "winetasteclasses": "Arts and Entertainment",
    "winetastingroom": "Nightlife",
    "winetours": "Arts and Entertainment",
    "wok": "Restaurants",
    "womenscloth": "Services",
    "workerscomplaw": "Services",
    "wraps": "Restaurants",
    "xmasmarkets": "Arts and Entertainment",
    "yelpevents": "Arts and Entertainment",
    "yoga": "Active Life",
    "youth_club": "Active Life",
    "yugoslav": "Restaurants",
    "zipline": "Active Life",
    "zoos": "Arts and Entertainment",
    "zorbing": "Active Life"
};

export default categoryMapping;

